version: 2.1

jobs:
  build:
    docker:
<<<<<<< HEAD
      - image: cimg/openjdk:8.0  # Remplacez par l'image appropriée
=======
      - image: cimg/openjdk:8.0 
>>>>>>> 032be94a0f55e63202307705dea71988df74a351
    steps:
      - checkout
      - run:
          name: Build Job
          command: echo "this is the build job"

  test:
    docker:
<<<<<<< HEAD
      - image: cimg/openjdk:8.0  # Utilisez la même image que dans le job de build
=======
      - image: cimg/openjdk:8.0
>>>>>>> 032be94a0f55e63202307705dea71988df74a351
    steps:
      - checkout
      - run:
          name: Test Job
          command: echo "this is the test job"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
