version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:8.0
    steps:
      - checkout
      - run:
          name: Build Job
          command: echo "this is the build job"

  test:
    docker:
      - image: cimg/openjdk:8.0
    steps:
      - checkout
      - run:
          name: Test Job
          command: echo "this is the test job"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build