name: Checkstyle Badge

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven and Run Checkstyle
        run: mvn clean verify

      - name: Extract Checkstyle Result
        id: checkstyle
        run: |
          if grep -q "<error" target/checkstyle-result.xml; then
            echo "::set-output name=status::errors"
          else
            echo "::set-output name=status::no-errors"
          fi

      - name: Update Badge
        uses: tj-actions/badge@v1
        with:
          label: "Checkstyle"
          status: "${{ steps.checkstyle.outputs.status }}"
          color: ${{ steps.checkstyle.outputs.status == 'errors' && 'red' || 'brightgreen' }}
          path: "checkstyle-badge.svg"
